name: Deploy to AWS

on:
  push:
    branches:
      - despliegue-aws  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html
            # Sincronizamos con GitHub sin tocar el archivo .env
            sudo git fetch --all
            sudo git reset --hard origin/despliegue-aws
            
            # Limpieza de basura y archivos temporales
            sudo git clean -fd -e .env
            
            # Asegurar permisos para evitar errores de escritura/cache
            sudo chown -R www-data:www-data /var/www/html/writable
            sudo chmod -R 775 /var/www/html/writable
            
            # Limpiar cache de CodeIgniter
            php spark cache:clear